spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/newsdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

